### ISSUE TITLE
Needs to be updated for Node 16

### ISSUE THREAD

**Issue by Tastyfish** [Wayland-Smithy/emoji-stripper-action#1]
GH Actions is discontinuing Node 12 in favor of Node 16.

This usually just requires updating [actions.yml](https://github.com/Wayland-Smithy/emoji-stripper-action/blob/master/action.yml) to say `node16` instead of `node12` but there could be side effects.

**Comment by Wayland-Smithy** [comment]
Thanks for the heads up 👍
